# 1 Basics about packages

## 1.1 listing or removing objects and functions on the workspace

`ls(all=T)` \# lists

`rm(list=ls(all=T))` \# removes all objects

## 1.2 installing and loading new packages

`install.packages(c("list", "of", "packages"))` \# general function and argument

`install.packages(c("zipfR", "languageR", "rpart", "chron", "Hmisc", "Matrix", "lme4", "coda", "e1071", "ape", "tidyverse"))` \# list from Baayen's 2008

`library("package")` \# general function and argument

`library("tidyverse")` \# example function and argument

## 1.2 Working with tables

### 1.2.1 Creating a table

`Filler <- c("aeh", "silence", "aehm")`

`Frequency <- c(394,332, 274)`

`myframe <- data.frame(Filler, Frequency); myframe`

### 1.2.2 Saving and loading data frames \# title is "myframe"

`write.table(myframe, "data_processed/myframe.txt", quote=FALSE, sep="\t", row.names=F, col.names=T)` \# note about row.names: "FALSE" will create a table without the row numbers (which makes it fit correctly in Excel). "TRUE" includes the row numbers

`mynewdataframe <- read.table(file.choose(), header=TRUE, sep="\t")` \# loads a txt file

### 1.3 plots (later)

# 2 Manipulating data frames

#### 2.1 Basic info check

`str(p3future)` \# checks structure

`head(p3future, 10)`

`tail(p3future, 10)`

#### 2.2 Navigating \# table_name[rows,columns]

p3future[1,] \# displays first row

p3future[,1] \# displays 1st column

p3future[1:3,] \# displays 1st to 3rd columns

p3future[3,1] \# displays 3rd row of the 1st column

p3future[1,] \# displays

#### 2.3 Focusing on specific values in rows/columns

`p3future[p3future$ASSOC=="WILL",]` \# displays only rows with WILL

`p3future[p3future$ASSOC=="GOING_TO",]` \# displays rows with GOING_TO

`p3future[p3future$SIGNIF=="*****",]` \# displays rows with \*\*\*\*\* significance

`p3future[p3future$SIGNIF!="ns",]` \# displays only rows with ns significance

`p3future[p3future$SIGNIF!="ns" & p3future$ASSOC=="WILL",]` \# displays ns significance for WILL

`p3future[p3future$SIGNIF!="ns" & p3future$ASSOC=="GOING_TO",]` \# displays ns significance for GOING_TO

# 3 Frequencies
